# Generated by Django 5.2.7 on 2025-11-15 19:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_alter_zapato_precio_alter_zapato_preciooferta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrito",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fechaCreacion", models.DateField(auto_now_add=True, verbose_name="Fecha de Creación")),
                ("fechaActualizacion", models.DateField(auto_now=True, verbose_name="Fecha de Actualización")),
                ("sesion", models.CharField(blank=True, max_length=100, null=True, verbose_name="ID de Sesión")),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carritos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrito",
                "verbose_name_plural": "Carritos",
                "ordering": ["-fechaCreacion"],
            },
        ),
        migrations.CreateModel(
            name="ZapatoCarrito",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cantidad",
                    models.IntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Cantidad"
                    ),
                ),
                ("talla", models.IntegerField(verbose_name="Talla")),
                ("fechaCreacion", models.DateField(auto_now_add=True, verbose_name="Fecha de Creación")),
                ("fechaActualizacion", models.DateField(auto_now=True, verbose_name="Fecha de Actualización")),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="zapatos", to="carrito.carrito"
                    ),
                ),
                (
                    "zapato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="zapatos_carrito", to="catalog.zapato"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zapato del Carrito",
                "verbose_name_plural": "Zapatos del Carrito",
                "ordering": ["-fechaCreacion"],
            },
        ),
    ]
