# Generated by Django 5.2.7 on 2025-11-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrito", "0001_initial"),
        ("catalog", "0005_alter_zapato_precio_alter_zapato_preciooferta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zapatocarrito",
            name="zapato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="zapatos_carrito", to="catalog.zapato"
            ),
        ),
    ]
