# Generated by Django 5.2.7 on 2025-11-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_categoria_id_alter_imagenzapato_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="categorias/", verbose_name="Imagen de la Categoría"
            ),
        ),
        migrations.AlterField(
            model_name="imagenzapato",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="zapatos/", verbose_name="Imagen del Zapato"),
        ),
        migrations.AlterField(
            model_name="marca",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="marcas/", verbose_name="Imagen de la Marca"),
        ),
    ]
