# Generated by Django 5.2.7 on 2025-11-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_categoria_imagen_alter_imagenzapato_imagen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zapato",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="zapatos/", verbose_name="Imagen del Zapato"),
        ),
        migrations.DeleteModel(
            name="ImagenZapato",
        ),
    ]
