# Generated by Django 5.2.7 on 2025-11-12 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_zapato_imagen_delete_imagenzapato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zapato",
            name="precio",
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="Precio"),
        ),
        migrations.AlterField(
            model_name="zapato",
            name="precioOferta",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Precio de Oferta",
            ),
        ),
    ]
