# Generated by Django 5.2.7 on 2025-11-12 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_zapato_precio_alter_zapato_preciooferta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zapato",
            name="precio",
            field=models.DecimalField(
                "Precio",
                max_digits=10,
                decimal_places=2,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="zapato",
            name="precioOferta",
            field=models.DecimalField(
                "Precio de oferta",
                blank=True,
                null=True,
                max_digits=10,
                decimal_places=2,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
