# Generated by Django 5.2.7 on 2025-11-14 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_alter_zapato_precio_alter_zapato_preciooferta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "codigo_pedido",
                    models.CharField(db_index=True, max_length=20, unique=True, verbose_name="Código de Pedido"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Creación")),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True, verbose_name="Fecha de Actualización")),
                (
                    "estado",
                    models.CharField(
                        choices=[("por_enviar", "Por Enviar"), ("en_envio", "En Envío"), ("recibido", "Recibido")],
                        default="por_enviar",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[("contrarembolso", "Contrarreembolso"), ("tarjeta", "Tarjeta")],
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                ("pagado", models.BooleanField(default=False, verbose_name="Pagado")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "coste_entrega",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Coste de Entrega",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                ("email", models.EmailField(max_length=254, verbose_name="Correo Electrónico")),
                ("telefono", models.CharField(max_length=15, verbose_name="Teléfono")),
                ("direccion_envio", models.TextField(verbose_name="Dirección de Envío")),
                ("ciudad_envio", models.CharField(max_length=100, verbose_name="Ciudad de Envío")),
                ("codigo_postal_envio", models.CharField(max_length=10, verbose_name="Código Postal de Envío")),
                ("direccion_facturacion", models.TextField(verbose_name="Dirección de Facturación")),
                ("ciudad_facturacion", models.CharField(max_length=100, verbose_name="Ciudad de Facturación")),
                (
                    "codigo_postal_facturacion",
                    models.CharField(max_length=10, verbose_name="Código Postal de Facturación"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("talla", models.IntegerField(verbose_name="Talla")),
                (
                    "cantidad",
                    models.IntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Cantidad"
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "zapato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.zapato", verbose_name="Zapato"
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pedido",
                "verbose_name_plural": "Items de Pedido",
                "unique_together": {("pedido", "zapato", "talla")},
            },
        ),
    ]
