# Generated by Django 5.2.7 on 2025-11-14 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_add_descuento_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["pagado", "fecha_creacion"], name="orders_pagado_fecha_idx"),
        ),
    ]
