# Generated by Django 5.2.7 on 2025-11-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_add_composite_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="ID del PaymentIntent (Stripe) o identificador de transacción del gateway",
                max_length=255,
                null=True,
                verbose_name="Stripe Payment Intent ID",
            ),
        ),
    ]
