# Generated by Django 5.2.7 on 2025-11-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="stripe_payment_intent_id",
        ),
    ]
